import { Metadata } from 'next';

import { Navigation } from '@components';

export const metadata: Metadata = {
  title: {
    template: '%s | Next.js 14 Lecture',
    default: 'Loading...',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
